apiVersion: v1
kind: Service
metadata:
  name: sample-spring-kotlin-microservice
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: sample-spring-kotlin-microservice
  ports:
  - port: 80
    targetPort: 8080
