apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: job-1
        image: ellerbrock/alpine-bash-git
        command: ["/bin/bash","-c","cd /data && git clone https://github.com/mohsen-mirzania/sample-spring-kotlin-microservice.git && cd sample-spring-kotlin-microservice"]
        volumeMounts:
        - name: vol
          mountPath: /data
      containers:
      - name: sleep
        image: ellerbrock/alpine-bash-git
        command: ["/bin/bash","-c","cd / && ls -a | tee output2.file"]
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: vol-claim
  backoffLimit: 0

